### ISSUE TITLE
Unable to generate a new site

### ISSUE THREAD

**Issue by matthewcheok** [toucansites/toucan#15]
I tried running `toucan generate ./src ./docs --base-url "http://localhost:3000/"` but got the following error `Error: missing`

**Comment by tib** [comment]
You have to run the generate command inside a Toucan project directory.

The minimal example is a good starting point: https://github.com/toucansites/minimal-example 

You can also take a look at these repositories for more inspiration:
- https://github.com/theswiftdev/blog
- https://github.com/toucansites/website
- https://github.com/swift-on-server/site

I'll improve the error message tho, so let's keep this issue open for a while.

**Comment by tib** [comment]
The improved error messages are now available on the main branch, the feature will be part of the 1.0.0-alpha.2 release.
