### ISSUE TITLE
Theme doesn't apply

### ISSUE THREAD

**Issue by artemnovichkov** [toucansites/toucan#45]
I followed the docs and tried to convert a README into a site. Everything works locally, but there is no theme after deploy on GitHub Pages.

Here is a site:
https://artemnovichkov.github.io/awesome-swift-charts/

Here is a source code:
https://github.com/artemnovichkov/awesome-swift-charts

Toucan version: 1.0.0-beta.1

What am I doing wrong?

**Comment by artemnovichkov** [comment]
Got it. Because the final link is https://artemnovichkov.github.io/awesome-swift-charts/, the stylesheet paths must be:

```html
<link rel="stylesheet" href="/awesome-swift-charts/css/theme.css">
<link rel="stylesheet" href="/awesome-swift-charts/css/style.css">
```

But it doesn't work locally.

**Comment by tib** [comment]
Have to add `{{site.baseUrl}}` before the css links, since GitHub page URLs contain a folder…

**Comment by tib** [comment]
Also, would you like to showcase your site on [toucansites.com](https://toucansites.com/showcases/)? I'd be happy if we could add it as a reference. 🙏

**Comment by artemnovichkov** [comment]
Yes, sure, why not! I'm going to improve it, and maybe I'll write a blog post.
