### ISSUE TITLE
Copy anchor links

### ISSUE THREAD

**Issue by artemnovichkov** [toucansites/toucan#46]
I like how anchors work in Github README - you can hover a title, a small icon appears at the left, and you can copy a link to a certain part of a page. Is it possible to copy this behaviour?

**Comment by tib** [comment]
We do have anchor support for the generated HTML, although we don’t highlight the headings with the icons on hover, i think it’s relatively easy to copy this behavior using a small CSS snippet.

**Comment by artemnovichkov** [comment]
Thanks, I'll try to find an example!
